In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/craigslist-vehicles/craigslist_vehicles.csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('D:\Code\Python\Data Science\craigslist\SampleCraigslist.csv')

df.info

<bound method DataFrame.info of        Unnamed: 0.1  Unnamed: 0          id  \
0                 0      362773  7307679724
1                 1      362712  7311833696
2                 2      362722  7311441996
3                 3      362771  7307680715
4                 4      362710  7311834578
...             ...         ...         ...
19995         19995      123181  7315021511
19996         19996      121806  7316459411
19997         19997      122376  7315894042
19998         19998      122352  7315909530
19999         19999      123504  7314773935

                                                     url   region  \
0      https://abilene.craigslist.org/ctd/d/abilene-2...  abilene
1      https://abilene.craigslist.org/ctd/d/abilene-2...  abilene
2      https://abilene.craigslist.org/ctd/d/abilene-2...  abilene
3      https://abilene.craigslist.org/ctd/d/abilene-2...  abilene
4      https://abilene.craigslist.org/ctd/d/abilene-2...  abilene
...                                                  ...      ...
19995  https://atlanta.craigslist.org/nat/ctd/d/atlan...  atlanta
19996  https://atlanta.craigslist.org/nat/ctd/d/atlan...  atlanta
19997  https://atlanta.craigslist.org/nat/ctd/d/atlan...  atlanta
19998  https://atlanta.craigslist.org/nat/ctd/d/atlan...  atlanta
19999  https://atlanta.craigslist.org/nat/ctd/d/atlan...  atlanta

                           region_url  price    year manufacturer  \
0      https://abilene.craigslist.org   4500  2002.0          bmw
1      https://abilene.craigslist.org   4500  2002.0          bmw
2      https://abilene.craigslist.org   4900  2006.0       toyota
3      https://abilene.craigslist.org   6500  2008.0         ford
4      https://abilene.craigslist.org   6500  2008.0         ford
...                               ...    ...     ...          ...
19995  https://atlanta.craigslist.org  39590  2020.0       subaru
19996  https://atlanta.craigslist.org  31990  2020.0       toyota
19997  https://atlanta.craigslist.org  35990  2020.0       toyota
19998  https://atlanta.craigslist.org  31990  2020.0       toyota
19999  https://atlanta.craigslist.org  27590  2020.0   volkswagen

                        model  ...    type paint_color  \
0                          x5  ...     NaN         NaN
1                          x5  ...     NaN         NaN
2                       camry  ...   sedan      silver
3                  expedition  ...     NaN         NaN
4                  expedition  ...     NaN         NaN
...                       ...  ...     ...         ...
19995        wrx sti sedan 4d  ...   sedan      silver
19996  rav4 xle premium sport  ...   other         red
19997   sienna xle minivan 4d  ...     van       white
19998    tacoma access cab sr  ...  pickup      silver
19999    golf gti s hatchback  ...   sedan       black

                                               image_url  \
0      https://images.craigslist.org/00m0m_iba78h8ty9...
1      https://images.craigslist.org/00m0m_iba78h8ty9...
2      https://images.craigslist.org/00808_5FkOw2aGjA...
3      https://images.craigslist.org/00M0M_i9CoFvVq8o...
4      https://images.craigslist.org/00M0M_i9CoFvVq8o...
...                                                  ...
19995  https://images.craigslist.org/00q0q_kQHK2O49f2...
19996  https://images.craigslist.org/00404_2wRXznoFeM...
19997  https://images.craigslist.org/00R0R_lwWjXSEWNa...
19998  https://images.craigslist.org/00i0i_61gjgngG17...
19999  https://images.craigslist.org/00J0J_7yElBTAW8Q...

                                             description county state  \
0      $4,500 Cash  2002 BMW X5  8 cylinder 4.4L moto...    NaN    tx
1      $4,500 Cash  2002 BMW X5  8 cylinder 4.4L moto...    NaN    tx
2      2006 TOYOTA CAMRY LE Sedan   Ready To Upgrade ...    NaN    tx
3      $6500.00 2008 Ford Expedition  8 cylinder 5.4L...    NaN    tx
4      $6500.00 2008 Ford Expedition  8 cylinder 5.4L...    NaN    tx
...                                                  ...    ...   ...
19995  Carvana is the safer way to buy a car During t...    NaN    ga
19996  Carvana is the safer way to buy a car During t...    NaN    ga
19997  Carvana is the safer way to buy a car During t...    NaN    ga
19998  Carvana is the safer way to buy a car During t...    NaN    ga
19999  Carvana is the safer way to buy a car During t...    NaN    ga

             lat       long               posting_date  \
0      32.401556 -99.884713  2021-04-16 00:00:00+00:00
1      32.401556 -99.884713  2021-04-24 00:00:00+00:00
2      32.453848 -99.787900  2021-04-23 00:00:00+00:00
3      32.401556 -99.884713  2021-04-16 00:00:00+00:00
4      32.401556 -99.884713  2021-04-24 00:00:00+00:00
...          ...        ...                        ...
19995  33.860000 -84.420000  2021-04-30 00:00:00+00:00
19996  33.860000 -84.420000  2021-05-03 00:00:00+00:00
19997  33.860000 -84.420000  2021-05-02 00:00:00+00:00
19998  33.860000 -84.420000  2021-05-02 00:00:00+00:00
19999  33.860000 -84.420000  2021-04-30 00:00:00+00:00

                    removal_date
0      2021-05-02 00:00:00+00:00
1      2021-04-28 00:00:00+00:00
2      2021-05-25 00:00:00+00:00
3      2021-04-26 00:00:00+00:00
4      2021-05-12 00:00:00+00:00
...                          ...
19995  2021-05-21 00:00:00+00:00
19996  2021-05-27 00:00:00+00:00
19997  2021-05-19 00:00:00+00:00
19998  2021-05-16 00:00:00+00:00
19999  2021-05-21 00:00:00+00:00

[20000 rows x 29 columns]>

In [5]:
from pprint import pprint
from random import choice
# df.drive.fillna("awd",inplace=True)
# df.drive.value_counts(dropna=False)

cols = df.columns

for col in cols:
    if df[col].mode().count()>0:
     df[col].fillna(df[col].mode().iloc[0],inplace=True)
    else:
       df[col].fillna(choice(df[col]),inplace=True)

df["posting_date"]= pd.to_datetime(df["posting_date"])
df["removal_date"] = pd.to_datetime(df["removal_date"])


df.to_csv("Cleaned Data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 29 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  20000 non-null  int64
 1   Unnamed: 0    20000 non-null  int64
 2   id            20000 non-null  int64
 3   url           20000 non-null  object
 4   region        20000 non-null  object
 5   region_url    20000 non-null  object
 6   price         20000 non-null  int64
 7   year          20000 non-null  float64
 8   manufacturer  20000 non-null  object
 9   model         20000 non-null  object
 10  condition     20000 non-null  object
 11  cylinders     20000 non-null  object
 12  fuel          20000 non-null  object
 13  odometer      20000 non-null  float64
 14  title_status  20000 non-null  object
 15  transmission  20000 non-null  object
 16  VIN           20000 non-null  object
 17  drive         20000 non-null  object
 18  size          20000 non-null  object
 19  type          20000 non-null  object
 20  paint_color   20000 non-null  object
 21  image_url     20000 non-null  object
 22  description   20000 non-null  object
 23  county        0 non-null      float64
 24  state         20000 non-null  object
 25  lat           20000 non-null  float64
 26  long          20000 non-null  float64
 27  posting_date  20000 non-null  datetime64[ns, UTC]
 28  removal_date  20000 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](2), float64(5), int64(4), object(18)
memory usage: 4.4+ MB